$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.IO.Compression.FileSystem

# ---- locate workspace + jar (keep this script pure ASCII: PS 5.1 reads .ps1 as GBK) ----
# Locate the TerraFirmaCraft jar without hardcoding where this machine keeps it. These scripts live in
# <root>/tools and the jar is expected in the project root, so the path is derived rather than globbed. The previous
# version searched an absolute path, which meant the generators could only run on one machine - and could not run in
# CI at all, where the release workflow downloads the jar into exactly this root.
$root = Split-Path $PSScriptRoot -Parent
$tfcJarFile = Get-ChildItem (Join-Path $root '*TerraFirmaCraft*.jar') -File -ErrorAction SilentlyContinue | Select-Object -First 1
if (-not $tfcJarFile) { throw ('no TerraFirmaCraft jar in ' + $root + ': these generators read TFC textures and data out of it') }
$jar = $tfcJarFile.FullName
$root = Split-Path $jar -Parent
$tools = Join-Path $root 'tools'
$res = Join-Path $root 'src\main\resources'
$assets = Join-Path $res 'assets\tfc_food_port'
$langDir = Join-Path $assets 'lang'
$modelDir = Join-Path $assets 'models\item'
$texDir = Join-Path $assets 'textures\item'

New-Item -ItemType Directory -Force -Path $langDir, $modelDir, $texDir | Out-Null

$utf8 = New-Object System.Text.UTF8Encoding($false)
$enList = New-Object System.Collections.Generic.List[string]
$zhList = New-Object System.Collections.Generic.List[string]

function Add-Lang([string]$key, [string]$nameEn, [string]$nameZh) {
  $script:enList.Add('  "' + $key + '": "' + $nameEn + '"')
  $script:zhList.Add('  "' + $key + '": "' + $nameZh + '"')
}

# ---- translations that are not items (creative tab, block names) ----
foreach ($line in [System.IO.File]::ReadAllLines((Join-Path $tools 'extra-lang.tsv'), [System.Text.Encoding]::UTF8)) {
  if ([string]::IsNullOrWhiteSpace($line)) { continue }
  $p = $line.TrimStart([char]0xFEFF) -split "`t"
  if ($p.Count -ge 3) { Add-Lang $p[0].Trim() $p[1].Trim() $p[2].Trim() }
}

# ---- items ----
# Two sources: items.tsv holds everything copied out of the TFC jar, and mooncake-items.tsv holds the mooncakes,
# whose textures are not in TFC at all (gen-textures.ps1 draws them from the supplied template). Keeping them in a
# separate file means this script never looks for a mooncake texture in the TFC jar.
$itemFiles = @((Join-Path $tools 'items.tsv'), (Join-Path $tools 'mooncake-items.tsv'))
$z = [System.IO.Compression.ZipFile]::OpenRead($jar)
$missing = New-Object System.Collections.Generic.List[string]
$count = 0

foreach ($itemFile in $itemFiles) {
  if (-not (Test-Path $itemFile)) { throw ("missing item list " + $itemFile) }
  $lines = [System.IO.File]::ReadAllLines($itemFile, [System.Text.Encoding]::UTF8)

  for ($i = 0; $i -lt $lines.Count; $i++) {
    $line = $lines[$i]
    if ($i -eq 0) { $line = $line.TrimStart([char]0xFEFF) }
    if ([string]::IsNullOrWhiteSpace($line)) { continue }
    $parts = $line -split "`t"
    if ($parts.Count -lt 3) { Write-Output ('BAD LINE: ' + $line); continue }

    $id = $parts[0].Trim()
    $nameEn = $parts[1].Trim()
    $nameZh = $parts[2].Trim()
    $count++

    Add-Lang ('item.tfc_food_port.' + ($id -replace '/', '.')) $nameEn $nameZh

    # ---- item model ----
    $modelPath = (Join-Path $modelDir ($id -replace '/', '\')) + '.json'
    $modelParentDir = Split-Path $modelPath -Parent
    if (-not (Test-Path $modelParentDir)) { New-Item -ItemType Directory -Force -Path $modelParentDir | Out-Null }
    $modelJson = "{`n  `"parent`": `"minecraft:item/generated`",`n  `"textures`": {`n    `"layer0`": `"tfc_food_port:item/$id`"`n  }`n}`n"
    [System.IO.File]::WriteAllText($modelPath, $modelJson, $utf8)

    # ---- texture ----
    # Textures generated by gen-textures.ps1 have nothing to copy and nothing to report as missing: the mooncakes
    # and raw mooncakes come from the mooncake template, and the two golden apple jam jars are repainted versions of
    # an existing jam (there is no golden apple jar in the TFC data).
    # Every other item comes out of the TFC jar: food/ from item/food, food/jam/ from item/jar, seeds/ from item/seeds.
    $generated = ($id -like 'food/mooncake/*') -or ($id -like 'food/raw_mooncake/*') -or
                 ($id -eq 'food/jam/gold_apple') -or ($id -eq 'food/jam/enchanted_gold_apple')
    if ($generated) {
      if (-not (Test-Path ((Join-Path $texDir ($id -replace '/', '\')) + '.png'))) {
        throw ("$id has no texture: run tools/gen-textures.ps1 first")
      }
      continue
    }

    $srcEntry = $null
    if ($id -like 'food/jam/*') {
      $srcEntry = 'assets/tfc/textures/item/jar/' + $id.Substring('food/jam/'.Length) + '.png'
    } elseif ($id -like 'food/*') {
      $srcEntry = 'assets/tfc/textures/item/food/' + $id.Substring('food/'.Length) + '.png'
    } elseif ($id -like 'seeds/*') {
      $srcEntry = 'assets/tfc/textures/item/seeds/' + $id.Substring('seeds/'.Length) + '.png'
    }

    $texOut = (Join-Path $texDir ($id -replace '/', '\')) + '.png'
    $entry = $null
    if ($srcEntry) { $entry = $z.Entries | Where-Object { $_.FullName -eq $srcEntry } | Select-Object -First 1 }

    if ($entry) {
      $outDir = Split-Path $texOut -Parent
      if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Force -Path $outDir | Out-Null }
      [System.IO.Compression.ZipFileExtensions]::ExtractToFile($entry, $texOut, $true)
    } else {
      $missing.Add($id + '  <=  ' + $srcEntry)
    }
  }
}
$z.Dispose()

$enText = '{' + "`n" + ($enList -join ",`n") + "`n}" + "`n"
$zhText = '{' + "`n" + ($zhList -join ",`n") + "`n}" + "`n"
[System.IO.File]::WriteAllText((Join-Path $langDir 'en_us.json'), $enText, $utf8)
[System.IO.File]::WriteAllText((Join-Path $langDir 'zh_cn.json'), $zhText, $utf8)

Write-Output ('items processed: ' + $count)
Write-Output ('english entries: ' + $enList.Count + '   chinese entries: ' + $zhList.Count)
if ($missing.Count -gt 0) {
  Write-Output '--- textures missing from the TFC jar (placeholders needed) ---'
  $missing | ForEach-Object { Write-Output $_ }
}
